apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: internal-ip-space
      protocol: layer2
      addresses:
      - 192.0.2.240/28
