apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jjo-logspam
  name: jjo-logspam
  namespace: jjo
spec:
  template:
    metadata:
      labels:
        app: jjo-logspam
    spec:
      restartPolicy: Never
      containers:
      - image: xjjo/logspam
        name: logspam
        args: ["--str-len", "45", "--one-off", "100000"]
