// Code generated by protoc-gen-go from "httpreq.proto"
// DO NOT EDIT!

package http

import "goprotobuf.googlecode.com/hg/proto"

type TYPE int32
const (
	TYPE_GET = 1
	TYPE_POST = 2
	TYPE_NONE = 3
)
var TYPE_name = map[int32] string {
	1: "GET",
	2: "POST",
	3: "NONE",
}
var TYPE_value = map[string] int32 {
	"GET": 1,
	"POST": 2,
	"NONE": 3,
}
func NewTYPE(x int32) *TYPE {
	e := TYPE(x)
	return &e
}

type Request struct {
	Type	*TYPE	"PB(varint,1,req,name=type,enum=http.TYPE,def=1)"
	Path	*string	"PB(bytes,2,req,name=path)"
	XXX_unrecognized	[]byte
}
func (this *Request) Reset() {
	*this = Request{}
}
func NewRequest() *Request {
	return new(Request)
}
const Default_Request_Type TYPE = TYPE_GET

func init() {
	proto.RegisterEnum("http.TYPE", TYPE_name, TYPE_value)
}
